server:
  port: 8088

spring:
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://elasticsearch_apix2019/apix2019?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: apix2019
  rabbitmq:
    host: rabbitmq_apix2019
    port: 5672

queue:
  kit-queue: apix-kit-queue
  recommendation-queue: apix-recommendation-queue
  notification-queue: apix-notification-queue

management:
  endpoints:
    web:
      exposure:
        include: "actuator,logfile,metrics,health,info"

logging:
  file: apix2019-kit.log
  level:
    root: info
